<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GraphicCardSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('graphic_cards')->insert([
            [
                'model_name'   => 'NVIDIA GeForce RTX 4090',
                'architecture' => 'Ada Lovelace',
                'vram_gb'      => 24,
                'memory_type'  => 'GDDR6X',
                'price_usd'    => 1599.00,
                'core_count'   => 16384,
                'tdp_watts'    => 450,
                'release_year' => 2022,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'model_name'   => 'NVIDIA GeForce RTX 4070 Super',
                'architecture' => 'Ada Lovelace',
                'vram_gb'      => 12,
                'memory_type'  => 'GDDR6X',
                'price_usd'    => 599.00,
                'core_count'   => 7168,
                'tdp_watts'    => 220,
                'release_year' => 2024,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'model_name'   => 'AMD Radeon RX 7900 XTX',
                'architecture' => 'RDNA 3',
                'vram_gb'      => 24,
                'memory_type'  => 'GDDR6',
                'price_usd'    => 999.00,
                'core_count'   => 6144,
                'tdp_watts'    => 355,
                'release_year' => 2022,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'model_name'   => 'AMD Radeon RX 7600',
                'architecture' => 'RDNA 3',
                'vram_gb'      => 8,
                'memory_type'  => 'GDDR6',
                'price_usd'    => 269.00,
                'core_count'   => 2048,
                'tdp_watts'    => 165,
                'release_year' => 2023,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'model_name'   => 'Intel Arc A770',
                'architecture' => 'Alchemist',
                'vram_gb'      => 16,
                'memory_type'  => 'GDDR6',
                'price_usd'    => 349.00,
                'core_count'   => 4096,
                'tdp_watts'    => 225,
                'release_year' => 2022,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'model_name'   => 'NVIDIA GeForce RTX 4080',
                'architecture' => 'Ada Lovelace',
                'vram_gb'      => 16,
                'memory_type'  => 'GDDR6X',
                'price_usd'    => 1199.00,
                'core_count'   => 9728,
                'tdp_watts'    => 320,
                'release_year' => 2022,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'model_name'   => 'NVIDIA GeForce RTX 4070 Ti',
                'architecture' => 'Ada Lovelace',
                'vram_gb'      => 12,
                'memory_type'  => 'GDDR6X',
                'price_usd'    => 799.00,
                'core_count'   => 7680,
                'tdp_watts'    => 285,
                'release_year' => 2023,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'model_name'   => 'AMD Radeon RX 7900 XT',
                'architecture' => 'RDNA 3',
                'vram_gb'      => 20,
                'memory_type'  => 'GDDR6',
                'price_usd'    => 899.00,
                'core_count'   => 5376,
                'tdp_watts'    => 320,
                'release_year' => 2022,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'model_name'   => 'NVIDIA GeForce RTX 4060',
                'architecture' => 'Ada Lovelace',
                'vram_gb'      => 8,
                'memory_type'  => 'GDDR6',
                'price_usd'    => 299.00,
                'core_count'   => 3584,
                'tdp_watts'    => 115,
                'release_year' => 2023,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'model_name'   => 'AMD Radeon RX 7800 XT',
                'architecture' => 'RDNA 3',
                'vram_gb'      => 16,
                'memory_type'  => 'GDDR6',
                'price_usd'    => 499.00,
                'core_count'   => 3840,
                'tdp_watts'    => 263,
                'release_year' => 2023,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'model_name'   => 'NVIDIA GeForce RTX 4060 Ti',
                'architecture' => 'Ada Lovelace',
                'vram_gb'      => 8,
                'memory_type'  => 'GDDR6',
                'price_usd'    => 399.00,
                'core_count'   => 2560,
                'tdp_watts'    => 130,
                'release_year' => 2023,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'model_name'   => 'AMD Radeon RX 7700 XT',
                'architecture' => 'RDNA 3',
                'vram_gb'      => 12,
                'memory_type'  => 'GDDR6',
                'price_usd'    => 399.00,
                'core_count'   => 2560,
                'tdp_watts'    => 250,
                'release_year' => 2023,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'model_name'   => 'Intel Arc B580',
                'architecture' => 'Battlemage',
                'vram_gb'      => 12,
                'memory_type'  => 'GDDR6',
                'price_usd'    => 249.00,
                'core_count'   => 2048,
                'tdp_watts'    => 190,
                'release_year' => 2025,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'model_name'   => 'NVIDIA GeForce RTX 5090',
                'architecture' => 'Blackwell',
                'vram_gb'      => 32,
                'memory_type'  => 'GDDR7',
                'price_usd'    => 1999.00,
                'core_count'   => 21760,
                'tdp_watts'    => 575,
                'release_year' => 2025,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'model_name'   => 'NVIDIA GeForce RTX 5080',
                'architecture' => 'Blackwell',
                'vram_gb'      => 16,
                'memory_type'  => 'GDDR7',
                'price_usd'    => 999.00,
                'core_count'   => 10240,
                'tdp_watts'    => 320,
                'release_year' => 2025,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
        ]);
    }
}